### ISSUE TITLE
GitLocalize

### ISSUE THREAD

**Issue by alexture** [mmazzarolo/breathly-app#101]
Adding GitLocalize to the project would allow volunteers to translate the (written part of the) app with no effort on your end: https://docs.gitlocalize.com/getting_started.html

A bit of documentation on where to put the voice strings & how to add them in a pull request would allow non-technical people who have good mics to record themselves and add the strings in their locale.

Linked to: #72 & #62 with other people who wanted to volunteer for translation (personally I'm happy to help with French).

**Comment by mmazzarolo** [comment]
Hey @alexture! Thanks, never heard of GitLocalize before. Let me finish publishing the new version on the store (they're complaining about random things, as always) and I'll look into this 👍

**Comment by mmazzarolo** [comment]
Closing — let's continue the discussion in #62 .
