### ISSUE TITLE
Custom patterns creation

### ISSUE THREAD

**Issue by esmoak** [mmazzarolo/breathly-app#19]
I can't thank you enough for this app. I've wanted a FOSS replacement for Prana Breath on Android for a long time.

(Speaking of, looks like #7 might be able to be closed.)

It would be great if we could input our own pattern into the app. Like fill in four boxes for number of seconds for Inhale-Retain-Exhale-Sustain.

Also since you mentioned in the readme that you used other apps to clone the patterns in your app, please consider some from Prana Breath. There is a particular one for calming that is basically 3-0-6-6 (or 3-0-6-9 in more advanced mode). I'd love to see that pattern and a couple others, but inputting our own pattern would also work.

Thank you so much. 

Edit: there is a typo in description for Ujjayi. It says "styste"  when I think you meant "system."

**Comment by mmazzarolo** [comment]
Thank you @esmoak !

> (Speaking of, looks like #7 might be able to be closed.)

It looks like I have to setup fastlane or an automated deploying tool first, which is really time consuming so I'm not sure I'll be able to do it soon :/ 

> It would be great if we could input our own pattern into the app. Like fill in four boxes for number of seconds for Inhale-Retain-Exhale-Sustain.

I just added the voice-guided-breathing, which was my top requested feature (from the Play Store reviews). It's going to be published soon. 
My next item in the to-do-list is definitely adding a customizable timing 👍 

> Also since you mentioned in the readme that you used other apps to clone the patterns in your app, please consider some from Prana Breath. There is a particular one for calming that is basically 3-0-6-6 (or 3-0-6-9 in more advanced mode). I'd love to see that pattern and a couple others, but inputting our own pattern would also work.

Nice! adding new techniques is a piece of cake. 
If you think this is worth the effort I can add it asap. Does this pattern also have a description/name? 
If it does not, if you could just write down a generic description (the one that appears in the pattern picker) about it it would be great. 
FYI in the future I'm planning to explore how to make the pattern picker more efficient to navigate. 

> Edit: there is a typo in description for Ujjayi. It says "styste" when I think you meant "system."

Will fix, thanks!

**Comment by esmoak** [comment]
I mentioned that issue since since your app is now on F-Droid (not sure if you knew it went through it not). Maybe add a download from F-Droid link on the website if you want?

 https://f-droid.org/app/com.mmazzarolo.breathly

The breathing pattern is called Relax and is listed here: https://pranabreath.info/index.php?title=Relax

I don't know what type of copywrite it licensing the app falls under, but from the wiki: 

"Effects

    relaxing the everyday pressure
    relieving physical tension
    feeling less stressed
    switching to resting in an faster and easier way
    enabling high quality recreation
    helping to fall asleep faster"

Other patterns here:
https://pranabreath.info/wiki/index.php?title=Training_type

The above wiki lists the ratios instead of the seconds since the app allows one to customize the times.

**Comment by mmazzarolo** [comment]
> I mentioned that issue since since your app is now on F-Droid (not sure if you knew it went through or not). Maybe add a download from F-Droid link on the website if you want?

I wasn't aware of it 😅I'll add a link. 

> The breathing pattern is called Relax and is listed here: https://pranabreath.info/index.php?title=Relax

Thanks! I'll see if we can add it by adding a reference to the Prana Breath wiki

**Comment by esmoak** [comment]
To be fair, I don't think any of the other app's patterns are protected by a license, since even their wiki lists the sources for the patterns as being much more ancient. I just mentioned that just to be on the safe side. I just wouldn't copy their description without proper citation, but you know that already.

Thanks again for the app.

**Comment by mmazzarolo** [comment]
Closed by #35 👍
