### ISSUE TITLE
Respect back button behaviour on Android

### ISSUE THREAD

**Issue by akwick** [mmazzarolo/breathly-app#20]
Android version: Android 8.0.0 
Breathly version: 1.4 

Observed behaviour: 
I start the application, click on settings or the breath technique button, wait until the new screen, pressing the hardware back button of my phone and I observe that the app closes.

Expected behaviour:
I expect the same behaviour as for the back button in the app.

**Comment by mmazzarolo** [comment]
@akwick thank you for the report, makes sense.

**Comment by mmazzarolo** [comment]
Fixed by #26
