### ISSUE TITLE
create and edit

### ISSUE THREAD

**Issue by Bebarr** [mmazzarolo/breathly-app#22]
This app is very usefull!! Does it will be possible in an upgrade to create our own breath part? This will be very helpful into my diving training:)

**Comment by mmazzarolo** [comment]
@Bebarr thanks! 
It's not possible yet, but it's planned, see https://github.com/mmazzarolo/breathly-app/issues/19
Unfortunately I can add new features only in my free time and right now I'm busy on another side project, so it might take a bit. If you have any design/programming experience you're more than welcome to add you suggestions on how this feature could be implemented!

**Comment by Bebarr** [comment]
Ok cool. No. unfortunately I don't know how to code... I'm just a user who like use open source & free apps.
I'll wait your upgrade ;)

**Comment by mmazzarolo** [comment]
Duplicated by #19
