### ISSUE TITLE
Prevent display from going to sleep while doing a breathing session

### ISSUE THREAD

**Issue by kumaranvpl** [mmazzarolo/breathly-app#3]
Hi,

I am using moto g4 plus with android 8.0(oreo).
My display sleep time is set to 15 seconds.
Because of that while doing a breathing session mobile's display turns off.
I could simply increase the sleep time to a larger number but that won't be a correct fix.
I would like to suggest you to implement some sort of display sleep prevention mechanism.
I think following package may help you with that
https://github.com/corbt/react-native-keep-awake

Thanks

**Comment by mmazzarolo** [comment]
Hi @kumaranvpl , thanks for opening the issue, this is actually a good idea. 
I'll give it a check 👍 (also, open to PRs of course)

**Comment by mmazzarolo** [comment]
Done! #11
