### ISSUE TITLE
Apply dark mode to exercices sessions

### ISSUE THREAD

**Issue by built2spill69** [mmazzarolo/breathly-app#31]
The themes are beautiful. Unfortunately, during exercising, the colors are the same as in light theme, which, at least in my case, is a bit eye straining during night. Thank you

**Comment by mmazzarolo** [comment]
Thanks for reporting. I think there's a chance here to decrease the contrast/light of the colors in dark mode. I'll check.

**Comment by mmazzarolo** [comment]
Closing in favour of #47, that has a more in depth explanation
