### ISSUE TITLE
Add support for a "pure/OLED" dark mode

### ISSUE THREAD

**Issue by sojusnik** [mmazzarolo/breathly-app#47]
It would be very helpful, if the app could run in the background even if the screen is turned off. At the moment it's not possible on Android 9. Disabling battery optimization for this app didn't help.

I solely rely on voice/sound as a guide and therefore want to turn off the display to save energy. If that's not possible technically, a complete dark mode, with minimalistic graphical elements, would also do the trick, provided that you have an AMOLED screen.

Irrespective of that, your app is a gem, thanks for creating it!

**Comment by mmazzarolo** [comment]
Thanks @sojusnik for the feedback :) 
Unfortunately I think you nailed it: the main problem is that, technically, this is not easy to do (or at least it will require several changes). 
That said, the requests for a "pure" dark mode (with a real black background) seems to have spiked in the last few months, so it will probably be the next feature I'll work on 👍

**Comment by sojusnik** [comment]
> Unfortunately I think you nailed it: the main problem is that, technically, this is not easy to do (or at least it will require several changes).

Just realized that even with an active display your app isn't running in the background. My use case in this situation is reading an epub while your app should give auditory hints in the background to maintain a certain breathing ratio.

Should I open a new issue regarding background activity or do you think that this is out of scope for this app?

**Comment by G-i-o** [comment]
Just wanted to suggest few apps that run in the background with screen on or off. As they are opensource, you might be able to take some of their code and integrate it into Breathly just with some adjustment rather than having to make "several changes"?

Lineage own Music Player
OpenTracks
OsmAnd~
AudioAnchor

@mmazzarolo :pray:

**Comment by mmazzarolo** [comment]
@G-i-o , I think this was meant to be posted in #54 ?
I'll add a comment there.

**Comment by G-i-o** [comment]
@mmazzarolo 

Maybe both. According to the comment above, this issue was started solely as alternative to the #54 one but I guess you are right from the categorization perspective.

🙏🏼

**Comment by mmazzarolo** [comment]
Closing. I'm releasing Breathly v2, which fully redesign the app so many issues are not valid anymore. In this specific case, the new dark mode is really "dark" now. Still not pure black, but definitely darker than before. 
If you feel we should still add a pure black mode, let me know by creating a new issue — it's now way easier to implement than before 👍

**Comment by G-i-o** [comment]
Looking forward to see this upgrade in F-Droid repos and than consider if pure black is needed or not.

Great work. Thank YOU!
