### ISSUE TITLE
please add more breathing pattern 

### ISSUE THREAD

**Issue by mbraeutig** [mmazzarolo/breathly-app#48]
please add more breathing pattern 
for example:

https://pranabreath.info/index.php?title=Prana_Breath_Wiki

**Comment by mmazzarolo** [comment]
Hey @mbraeutig ! You can now create your own custom pattern 👍 
If you think we should add new patterns, could you add a few more informations?
- Name of the pattern
- Durations of the pattern
- Description of the pattern
- Color of the pattern (making sure it stays on the pastel-tone and do not clash with the existing colors)? 

Feel free to create a new issue :) Thanks!

**Comment by mbraeutig** [comment]
yes i know,
but only ONE custom pattern.

Bye the way,
thank you for the great app
