### ISSUE TITLE
Custom session length

### ISSUE THREAD

**Issue by G-i-o** [mmazzarolo/breathly-app#51]
Hi. First, THANK YOU 🙏🏽 for this simple and yet beautifully empowering app. In 20yrs years this is the very first time I've managed to stick AND enjoy breathing exercises....all thanks to this app. Before I tried alone but counting while trying to focus on the breath at the same time made it challenging and eventually the sessions became daunting.

With this I'd like to request to add more options on the length of the sessions. The longest session is 7min but it would be useful to have some more pre-set like 10min, 15min, 20min ....or, **better**, to have the option to increase manually as it has been done  in the Android timer or Android alarm settings.

Much appreciated. 🙏🏽🙏🏽

![Alarm-Type Length Settings](https://user-images.githubusercontent.com/36502493/86939409-71841680-c139-11ea-97be-2fe7f9d5b86f.png)
![Timer-Type Length Settings](https://user-images.githubusercontent.com/36502493/86939415-721cad00-c139-11ea-87ee-1f975612ae6e.png)

**Comment by mmazzarolo** [comment]
Hey @G-i-o , thanks, I'm glad you've found Breathly helpful 😄 
Regarding your request: it makes sense. I'm adding it to the list of things I'll work on when I have some free time and I'm able to get back to Breathly (quite busy with work nowadays).

**Comment by G-i-o** [comment]
Thank YOU. Much appreciated.

**Comment by mmazzarolo** [comment]
https://github.com/mmazzarolo/breathly-app/pull/65

**Comment by G-i-o** [comment]
Just popping in to say a big thank You for adding "Timer Customization". 🙏🏼
