### ISSUE TITLE
Timer customization

### ISSUE THREAD

**Issue by mmazzarolo** [mmazzarolo/breathly-app#58]
Should we add more customization options for the timers (in the settings screen)? How can we do so?

**Comment by sojusnik** [comment]
I think that [progressively extended periods](https://github.com/mmazzarolo/breathly-app/issues/50) and [custom sessions](https://github.com/mmazzarolo/breathly-app/issues/51) are a good start.

**Comment by mmazzarolo** [comment]
https://github.com/mmazzarolo/breathly-app/pull/65
