### ISSUE TITLE
F-Droid support

### ISSUE THREAD

**Issue by mmazzarolo** [mmazzarolo/breathly-app#60]
👋 thanks to @IzzySoft Breathly app is available on F-Droid. 

Unfortunately, the latest versions of Breathly [are not being published correctly on F-Droid](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.mmazzarolo.breathly.yml). I have 0 F-Droid experience: I don't know how to fix them and I'm worried it would take me a ton of time just trying to understand how it all works...  
If anyone is willing to help, that would be great! 
Any help and discussion is appreciated in this thread :)

**Comment by IzzySoft** [comment]
Unless you tell what exactly is "not correctly", it's hard to help. F-Droid just checks the tags and looks for those named `android-<versionName>`. The last such is 1.8, and that's there.

So could you please clarify what's wrong in your opinion?

**Comment by mmazzarolo** [comment]
> So could you please clarify what's wrong in your opinion?

Unfortunately, besides that metadata file, I have no idea where to start 😓

**Comment by mmazzarolo** [comment]
Just to clarify: @IzzySoft , I wasn't blaming you/F-Droid in my initial post (or at least that wasn't my intention). 

I just genuinely need/needed some help on this because I don't have any prior F-Droid experience and a few users in other threads seemed to know better than me where to look at, so I created a catch-all thread 👍

**Comment by IzzySoft** [comment]
@mmazzarolo no worries, I saw no blame anywhere – just confusion on what might be wrong. Looks like I was able to point out a possible culprit \o/

**Comment by clavelc** [comment]
Hi

There is a post dated October 14 about react native apps in Fdroid, not sure if it's relevant but since it's still an old version in the repoa thought I would share 👍 
[Adding React Native Apps to F-Droid](https://f-droid.org/fr/2020/10/14/adding-react-native-app-to-f-droid.html) 

Is there any way to get the latest apk in the meantime without the play store ?

Thanks, great app !

**Comment by licaon-kter** [comment]
so this can be closed?

**Comment by clavelc** [comment]
Well it’s still an old version on Fdroid...

**Comment by licaon-kter** [comment]
Oh, the old node issue, it's on my todo, brb :)

**Comment by BrandonKMLee** [comment]
Seconded this, we really need this to be the liberation of the mind.

**Comment by Poussinou** [comment]
It's now on F-Droid [here](https://f-droid.org/packages/com.mmazzarolo.breathly/) !

@mmazzarolo You can add a badge in the readme to help users get the app on F-Droid with [this picture](https://fdroid.gitlab.io/artwork/badge/get-it-on.png) ;)

**Comment by mmazzarolo** [comment]
@Poussinou thank you! Done in #95 :)
