### ISSUE TITLE
Add color/vibration guided breathing or just custom sound

### ISSUE THREAD

**Issue by fenymufyd** [mmazzarolo/breathly-app#63]
Instead of sound guided breathing i would like to have background color change per step instead (for example background color blue at breathe in, red at hold, green at breathe out and repeat), a vibration pattern instead of sound could be nice too or just customize your own sound because i dont like how it sounds and prefer a quieter subtle alternative sound

**Comment by mmazzarolo** [comment]
Hey! Thanks for the feedback/idea :) 
We're already using colors for theming the exercise type, so I don't think it's a viable solution using even more colors for distinguishing between the exercise phases.
A custom vibration pattern has already been requested a few times, and in my optioning is something that is definitely doable. Any idea on how to implement that in a meaningful way?

**Comment by mmazzarolo** [comment]
Closing. I'm releasing Breathly v2, which fully redesign the app so many issues are not valid anymore.
