### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by IzzySoft** [mmazzarolo/breathly-app#7]
F-Droid maintainer here. It [was requested](https://gitlab.com/fdroid/rfp/issues/1014) to include your app with F-Droid – and our scanner sees no issues with that. To further process this request, we'd like to know if you support it (or are at least not opposed to it). Can you please confirm?

If you're fine with having your app at F-Droid, there are two suggestions:

* could you please [tag your releases](https://github.com/mmazzarolo/breathly-app/releases)? That makes it clear which commit to build – and also enables us to automatically detect updates.
* nice to have: could you setup Fastlane or Triple-T structures with your app's repo here (see [here](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/) for some details)? That way you could provide screenshots, descriptions (even localized ones) and per-release changelogs not only for F-Droid, but also for Google Play; Fastlane as well as Triple-T work with both.

Thanks in advance, and looking forward to your decision! Whichever it might be: All the best for your app!

**Comment by mmazzarolo** [comment]
Hi @IzzySoft !
No issues at all with including it in F-Droid and tag the releases, but unfortunately I don't have enough time nowadays to setup Fastlane for it though (open to PR of course!)

Thanks for starting the discussion!

**Comment by IzzySoft** [comment]
Great to read, thanks! So let's keep Fastlane for later then. The most important thing is you agree having your app with us, and the second one were the tags which we now have. Just one more thing: the tag name must correspond to `versionName`. So could you make the tag name `v1.1`, which is what `versionName` says at that point? The leading `v` is fine (in fact, most apps use that). I'd then set the "version detector" for the tag to `Version v%v` (i.e. "tag name = `v`+`<versionName>`"), and this part should be fine.

**Comment by adolfintel** [comment]
Nice app. I noticed that the privacy policy says that the app uses google analytics, which is not allowed on f-droid. Did you remove it from the f-droid version?

**Comment by mmazzarolo** [comment]
@adolfintel thank you. 
Honestly, I wasn't aware the app was being published on F-Droid. 

That said, I just updated the privacy policy, which is valid only for the Play Store and was outdated: Breathly is **not** tracking users in any way 👍
