### ISSUE TITLE
4-7-11 Breathing Technique

### ISSUE THREAD

**Issue by sandoxy** [mmazzarolo/breathly-app#73]
There is a relatively new, scientifically proven breathing technique. It is called "4-7-11". It means: 4 sec inhale, 7 sec exhale and it should last 11 minutes. The technique comes from Germany, so I did not find any good sites in English. But you could translate the sites, if you are interested. I give you some links to official sites:

https://www.daserste.de/information/wissen-kultur/w-wie-wissen/atemtraining-100.html
This site mentions the Breathly-App:)

https://www.psychologie-heute.de/gesundheit/artikel-detailansicht/39837-so-schoen-alltagstauglich.html

Maybe it is interesting for the app.

**Comment by BrandonKMLee** [comment]
There is also something similar in https://developer.chrome.com/blog/new-in-chrome-73/
> 7-11 BREATHING
> Breathe in for 7, exhale for 11.

> 5 - 5 - 10 BREATHING
> Breathe in for 5, hold for 5 and breathe out for 10.

**Comment by mmazzarolo** [comment]
Closing in favour of #80
