### ISSUE TITLE
"11 Breathing Practices to Get You Through a Rough Patch"

### ISSUE THREAD

**Issue by BrandonKMLee** [mmazzarolo/breathly-app#78]
- [ ] Karate Breathing (quick breath and hold for 6, quick out)
- [ ] Stimulating Breath, or Bellows Breath (Similar to Wim Hof, quick but stable in-out)
- [ ] Advanced Inhale-Hold-Exhale Deep Breathing (5-7-9)
- [ ] Box Breathing (4-4-4-4)
- [ ] Pranayama Breathing
- [ ] Pursed-Lip Breathing (1x in, no hold, 2x out)
- [ ] Relaxing Breath (4-7-8)
- [ ] The Long Exhale (5-5, 5-6, 5-7 ...)
- [ ] Coherent Breathing (6 seconds in, no hold, 6 seconds out)
- [ ] Sama Vritti (4-7-8)

Reference: https://medium.com/welltory/11-breathing-practices-to-get-you-through-a-rough-patch-cea987791dbe

**Comment by mmazzarolo** [comment]
Closing in favour of #80
