### ISSUE TITLE
Breathe Holding Test

### ISSUE THREAD

**Issue by BrandonKMLee** [mmazzarolo/breathly-app#79]
There is a feature in https://play.google.com/store/apps/details?id=com.havabee.breathe&hl=en_US&gl=US
That allows people to test their breath power. (I would assume that is meant for potential Wim Hof Method trainees)

**Comment by mmazzarolo** [comment]
Closing. I'm releasing Breathly v2, which fully redesign the app so many issues are not valid anymore. This is not something I'm planning to add for now, sorry. That said, I can definitely add a custom pattern for the Wim Of method.

**Comment by mmazzarolo** [comment]
#80
