### ISSUE TITLE
Sub-second resolution for custom timings

### ISSUE THREAD

**Issue by fabbra** [mmazzarolo/breathly-app#82]
Is there a chance to have a finer granularity for the timings to be adjusted in the custom settings (inhale, hold, exhale, and hold), e.g. being able to set 4.5 (increments of 0.5 s) or even 4.1 (increments of 0.1 s)?
Thanks a lot for this nice app.

**Comment by mmazzarolo** [comment]
Hello @fabbra ! 
Thanks for the feedback. I'll keep the issue around but FYI, this seems to be a lower priority feature than other ones 👍

**Comment by dinozarafonitis** [comment]
> Is there a chance to have a finer granularity for the timings to be adjusted in the custom settings (inhale, hold, exhale, and hold), e.g. being able to set 4.5 (increments of 0.5 s) or even 4.1 (increments of 0.1 s)? Thanks a lot for this nice app.

I would also like this feature, makes very much sense to have for further customisation on the breathing experience.
