### ISSUE TITLE
iOS: vibrate on step change

### ISSUE THREAD

**Issue by robogrobo** [mmazzarolo/breathly-app#85]
Vibrate on step change isn't working on iOS 14.6. If enabled in the settings and doing a breathing exercise, during a step change the phone doesn't vibrate. This setting would help a lot if you don't want to be focused to the screen.

**Comment by mmazzarolo** [comment]
Thanks for reporting @robogrobo :)

**Comment by mmazzarolo** [comment]
Closing. I'm releasing Breathly v2, which fully redesign the app so many issues are not valid anymore. The vibration on iOS should be working now 👍
