### ISSUE TITLE
A humble request🙏...

### ISSUE THREAD

**Issue by ghost** [mmazzarolo/breathly-app#86]
Your project is amazing🤩🤩. It is my fault that i can't understand how to import the project? My request is that
please give a complete steps  to import react native project on Android Studio...

I have searched on Google,YouTube, & StackOverflow and tried lot's of time but project is not import successfully. The error is still occured....

Build failed with an exception.  * What went wrong:  

Could not initialize class org.codehaus.groovy.runtime.InvokerHelper

**Comment by mmazzarolo** [comment]
Closing. I'm releasing Breathly v2, which fully redesign the app so many issues are not valid anymore.
