### ISSUE TITLE
Daily reminder notifications

### ISSUE THREAD

**Issue by kolgza** [mmazzarolo/breathly-app#88]
- Allow user to create reminders to perform specific breathing exercises at specific times.

A user might set a reminder to use the "Awake" technique at 8:00 AM, or the "Deep Calm" technique at 12:00 PM and 5:00 PM.

**Comment by BrandonKMLee** [comment]
Seconding on this, with reference from https://github.com/hovancik/stretchly/issues/987

**Comment by mmazzarolo** [comment]
Hey there! Thanks for the suggestion. For now, I feel this is out of the scope of what I had in mind with Breathly and it  would require a ton of work to implement. Maybe in the future we can come back to this 👍
