### ISSUE TITLE
better contrast with colors

### ISSUE THREAD

**Issue by wolftune** [mmazzarolo/breathly-app#90]
The subtle contrast is interesting, but if I use this with the Night Light feature on my device (or more strongly, wearing no-blue glasses in the evening), I can't see the circles changing *at all*, the contrast is basically invisible.

This seems related perhaps to https://github.com/mmazzarolo/breathly-app/issues/66 and https://github.com/mmazzarolo/breathly-app/issues/47

A good dark mode should *account* for Night/Light no-blue in the settings of it, and that could do it. But there could also be a high-contrast option regardless.

**Comment by mmazzarolo** [comment]
Closing. I'm releasing Breathly v2, which fully redesign the app so many issues are not valid anymore. In this specific case, the new dark mode is really "dark" now. Still not pure black, but definitely darker than before.
