### ISSUE TITLE
Add a sponsor button to the repo, cause thanks are nice but pay no bills. 

### ISSUE THREAD

**Issue by hacksenwerk** [mmazzarolo/breathly-app#97]
[Github Sponsor Button](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository)

**Comment by mmazzarolo** [comment]
Hey @hacksenwerk , thank you for the offer but I don't want to feel "tied" to this project. People paying or supporting it with money would pressure me into working on it, and I don't really have enough time to do so between family and my daily job. Thanks, though!
