### ISSUE TITLE
Can't scroll in the custom breathing technique page

### ISSUE THREAD

**Issue by gouchi** [mmazzarolo/breathly-app#98]
I can't reach the second hold parameter. I am running on small device which is 320 x 480.
![scrool](https://user-images.githubusercontent.com/7869503/184697322-1770e306-7bc1-4b11-b517-8b934e2465e8.png)

Please let me know if you need more debug.

Thank you.

**Comment by mmazzarolo** [comment]
Closing. I'm releasing Breathly v2, which fully redesign the app so many issues are not valid anymore. This issue should be fixed now.
